# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgsnewvectorlayerdialogbase.ui'
#
# Created: Thu Apr 13 15:47:40 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from qgis.gui import QgsProjectionSelectionWidget

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QgsNewVectorLayerDialogBase(object):
    def setupUi(self, QgsNewVectorLayerDialogBase):
        QgsNewVectorLayerDialogBase.setObjectName(_fromUtf8("QgsNewVectorLayerDialogBase"))
        QgsNewVectorLayerDialogBase.resize(444, 578)
        QgsNewVectorLayerDialogBase.setModal(True)
        self.gridlayout = QtGui.QGridLayout(QgsNewVectorLayerDialogBase)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.mFileEncoding = QtGui.QComboBox(QgsNewVectorLayerDialogBase)
        self.mFileEncoding.setEnabled(True)
        self.mFileEncoding.setObjectName(_fromUtf8("mFileEncoding"))
        self.gridlayout.addWidget(self.mFileEncoding, 5, 1, 1, 2)
        self.mFileFormatLabel = QtGui.QLabel(QgsNewVectorLayerDialogBase)
        self.mFileFormatLabel.setEnabled(True)
        self.mFileFormatLabel.setObjectName(_fromUtf8("mFileFormatLabel"))
        self.gridlayout.addWidget(self.mFileFormatLabel, 6, 0, 1, 1)
        self.mFileFormatComboBox = QtGui.QComboBox(QgsNewVectorLayerDialogBase)
        self.mFileFormatComboBox.setEnabled(True)
        self.mFileFormatComboBox.setObjectName(_fromUtf8("mFileFormatComboBox"))
        self.gridlayout.addWidget(self.mFileFormatComboBox, 6, 1, 1, 2)
        self.mFileFormatLabel_2 = QtGui.QLabel(QgsNewVectorLayerDialogBase)
        self.mFileFormatLabel_2.setEnabled(True)
        self.mFileFormatLabel_2.setObjectName(_fromUtf8("mFileFormatLabel_2"))
        self.gridlayout.addWidget(self.mFileFormatLabel_2, 5, 0, 1, 1)
        self.mCrsSelector = QgsProjectionSelectionWidget(QgsNewVectorLayerDialogBase)
        self.mCrsSelector.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mCrsSelector.setObjectName(_fromUtf8("mCrsSelector"))
        self.gridlayout.addWidget(self.mCrsSelector, 9, 0, 1, 3)
        self.buttonGroup1 = QtGui.QGroupBox(QgsNewVectorLayerDialogBase)
        self.buttonGroup1.setObjectName(_fromUtf8("buttonGroup1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.buttonGroup1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mPointRadioButton = QtGui.QRadioButton(self.buttonGroup1)
        self.mPointRadioButton.setObjectName(_fromUtf8("mPointRadioButton"))
        self.horizontalLayout.addWidget(self.mPointRadioButton)
        self.mLineRadioButton = QtGui.QRadioButton(self.buttonGroup1)
        self.mLineRadioButton.setObjectName(_fromUtf8("mLineRadioButton"))
        self.horizontalLayout.addWidget(self.mLineRadioButton)
        self.mPolygonRadioButton = QtGui.QRadioButton(self.buttonGroup1)
        self.mPolygonRadioButton.setObjectName(_fromUtf8("mPolygonRadioButton"))
        self.horizontalLayout.addWidget(self.mPolygonRadioButton)
        self.gridlayout.addWidget(self.buttonGroup1, 2, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(QgsNewVectorLayerDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 14, 0, 1, 3)
        self.groupBox = QtGui.QGroupBox(QgsNewVectorLayerDialogBase)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.textLabel1 = QtGui.QLabel(self.groupBox)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self.gridlayout1.addWidget(self.textLabel1, 0, 0, 1, 1)
        self.mNameEdit = QtGui.QLineEdit(self.groupBox)
        self.mNameEdit.setObjectName(_fromUtf8("mNameEdit"))
        self.gridlayout1.addWidget(self.mNameEdit, 0, 1, 1, 4)
        self.textLabel2 = QtGui.QLabel(self.groupBox)
        self.textLabel2.setObjectName(_fromUtf8("textLabel2"))
        self.gridlayout1.addWidget(self.textLabel2, 1, 0, 1, 1)
        self.mTypeBox = QtGui.QComboBox(self.groupBox)
        self.mTypeBox.setObjectName(_fromUtf8("mTypeBox"))
        self.gridlayout1.addWidget(self.mTypeBox, 1, 1, 1, 4)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout1.addWidget(self.label, 2, 0, 1, 1)
        self.mWidth = QtGui.QLineEdit(self.groupBox)
        self.mWidth.setObjectName(_fromUtf8("mWidth"))
        self.mWidth.setText("0")
        self.gridlayout1.addWidget(self.mWidth, 2, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout1.addWidget(self.label_2, 2, 3, 1, 1)
        self.mPrecision = QtGui.QLineEdit(self.groupBox)
        self.mPrecision.setObjectName(_fromUtf8("mPrecision"))
        self.gridlayout1.addWidget(self.mPrecision, 2, 4, 1, 1)
        self.mAddAttributeButton = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mAddAttributeButton.sizePolicy().hasHeightForWidth())
        self.mAddAttributeButton.setSizePolicy(sizePolicy)
        self.mAddAttributeButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionNewAttribute.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mAddAttributeButton.setIcon(icon)
        self.mAddAttributeButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mAddAttributeButton.setObjectName(_fromUtf8("mAddAttributeButton"))
        self.gridlayout1.addWidget(self.mAddAttributeButton, 4, 4, 1, 1)
        self.gridlayout.addWidget(self.groupBox, 10, 0, 1, 3)
        self.groupBox_2 = QtGui.QGroupBox(QgsNewVectorLayerDialogBase)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridlayout2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.mAttributeView = QtGui.QTreeWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mAttributeView.sizePolicy().hasHeightForWidth())
        self.mAttributeView.setSizePolicy(sizePolicy)
        self.mAttributeView.setAlternatingRowColors(True)
        self.mAttributeView.setRootIsDecorated(False)
        self.mAttributeView.setColumnCount(4)
        self.mAttributeView.setObjectName(_fromUtf8("mAttributeView"))
        self.gridlayout2.addWidget(self.mAttributeView, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(121, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout2.addItem(spacerItem, 3, 0, 1, 1)
        self.mRemoveAttributeButton = QtGui.QToolButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mRemoveAttributeButton.sizePolicy().hasHeightForWidth())
        self.mRemoveAttributeButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionDeleteAttribute.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mRemoveAttributeButton.setIcon(icon1)
        self.mRemoveAttributeButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mRemoveAttributeButton.setObjectName(_fromUtf8("mRemoveAttributeButton"))
        self.gridlayout2.addWidget(self.mRemoveAttributeButton, 3, 1, 1, 1)
        self.gridlayout.addWidget(self.groupBox_2, 12, 0, 1, 3)
        self.mFileFormatLabel.setBuddy(self.mFileFormatComboBox)
        self.mFileFormatLabel_2.setBuddy(self.mFileFormatComboBox)
        self.textLabel1.setBuddy(self.mNameEdit)
        self.textLabel2.setBuddy(self.mTypeBox)
        self.label.setBuddy(self.mWidth)
        self.label_2.setBuddy(self.mPrecision)


        self.mOkButton = self.buttonBox.button( QtGui.QDialogButtonBox.Ok )

        self.retranslateUi(QgsNewVectorLayerDialogBase)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), QgsNewVectorLayerDialogBase.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), QgsNewVectorLayerDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(QgsNewVectorLayerDialogBase)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mPointRadioButton, self.mLineRadioButton)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mLineRadioButton, self.mPolygonRadioButton)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mPolygonRadioButton, self.mFileEncoding)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mFileEncoding, self.mFileFormatComboBox)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mFileFormatComboBox, self.mCrsSelector)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mCrsSelector, self.mNameEdit)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mNameEdit, self.mTypeBox)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mTypeBox, self.mWidth)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mWidth, self.mPrecision)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mPrecision, self.mAddAttributeButton)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mAddAttributeButton, self.mAttributeView)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mAttributeView, self.mRemoveAttributeButton)
        QgsNewVectorLayerDialogBase.setTabOrder(self.mRemoveAttributeButton, self.buttonBox)

    def retranslateUi(self, QgsNewVectorLayerDialogBase):
        QgsNewVectorLayerDialogBase.setWindowTitle(_translate("QgsNewVectorLayerDialogBase", "New Shapefile Layer", None))
        self.mFileFormatLabel.setText(_translate("QgsNewVectorLayerDialogBase", "File format", None))
        self.mFileFormatLabel_2.setText(_translate("QgsNewVectorLayerDialogBase", "File encoding", None))
        self.buttonGroup1.setTitle(_translate("QgsNewVectorLayerDialogBase", "Type", None))
        self.mPointRadioButton.setText(_translate("QgsNewVectorLayerDialogBase", "Point", None))
        self.mLineRadioButton.setText(_translate("QgsNewVectorLayerDialogBase", "Line", None))
        self.mPolygonRadioButton.setText(_translate("QgsNewVectorLayerDialogBase", "Polygon", None))
        self.groupBox.setTitle(_translate("QgsNewVectorLayerDialogBase", "New field", None))
        self.textLabel1.setText(_translate("QgsNewVectorLayerDialogBase", "Name", None))
        self.textLabel2.setText(_translate("QgsNewVectorLayerDialogBase", "Type", None))
        self.label.setText(_translate("QgsNewVectorLayerDialogBase", "Length", None))
        self.label_2.setText(_translate("QgsNewVectorLayerDialogBase", "Precision", None))
        self.mAddAttributeButton.setToolTip(_translate("QgsNewVectorLayerDialogBase", "Add field to list", None))
        self.mAddAttributeButton.setText(_translate("QgsNewVectorLayerDialogBase", "Add to fields list", None))
        self.groupBox_2.setTitle(_translate("QgsNewVectorLayerDialogBase", "Fields list", None))
        self.mAttributeView.headerItem().setText(0, _translate("QgsNewVectorLayerDialogBase", "Name", None))
        self.mAttributeView.headerItem().setText(1, _translate("QgsNewVectorLayerDialogBase", "Type", None))
        self.mAttributeView.headerItem().setText(2, _translate("QgsNewVectorLayerDialogBase", "Length", None))
        self.mAttributeView.headerItem().setText(3, _translate("QgsNewVectorLayerDialogBase", "Precision", None))
        self.mRemoveAttributeButton.setToolTip(_translate("QgsNewVectorLayerDialogBase", "Delete selected field", None))
        self.mRemoveAttributeButton.setText(_translate("QgsNewVectorLayerDialogBase", "Remove field", None))

# from qgsprojectionselectionwidget import QgsProjectionSelectionWidget
